server:
  port: 9022 
spring: 
  application: 
    name: gateway-service-ratelimiter
  redis:
    host: localhost
    port: 6379
    database: 0   
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
      - id: limit_route
        uri: lb://SERVICE-B
        predicates:
        - Path=/demo/**
        filters:
        - StripPrefix=1
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@hostAddrKeyResolver}'
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 3
eureka: 
  client: 
    registerWithEureka: true
    serviceUrl: 
     defaultZone: http://eureka-002.com:7010/eureka/,http://eureka-001.com:7011/eureka/
        