package com.bj58.fang.codeGe.jsonObject;
import java.io.IOException;
import com.alibaba.fastjson.JSONObject;
public class Construct {
	public static void main(String[] args) throws IOException {
		JSONObject a = new JSONObject();
		a.put("tab_name", "租房");
		a.put("tab_key", "home");
		a.put("tab_icon_normal_url", "");
		a.put("tab_icon_selected_url", "");
		a.put("isLogin", false);
		a.put("isJumpOut", false);
		JSONObject a_target = new JSONObject();
		a.put("target", a_target);
		JSONObject a_target_protocol = new JSONObject();
		a_target.put("protocol", a_target_protocol);
		a_target_protocol.put("title", "租房");
		a_target_protocol.put("pagetype", "childCate");
		a_target_protocol.put("pullRefresh", true);
		JSONObject a_target_protocol_logParam = new JSONObject();
		a_target_protocol.put("logParam", a_target_protocol_logParam);
		a_target_protocol_logParam.put("webRefresh", "zfindex");
		a_target_protocol.put("showsift", true);
		a_target_protocol.put("list_name", "zufang");
		a_target_protocol.put("showpub", false);
		a_target_protocol.put("url", "https://houserent.m.58.com/web/list/@local@/zfhousevue.shtml?topcate=house&city=@local@");
		a_target.put("top_right_show", true);
		a_target.put("showim", false);
		a_target.put("top_right_text", "我是房东");
		a_target.put("pagetype", "childCate");
		JSONObject a_host_tab = new JSONObject();
		a.put("host_tab", a_host_tab);
		JSONObject a_host_tab_target = new JSONObject();
		a_host_tab.put("target", a_host_tab_target);
		JSONObject a_host_tab_target_protocol = new JSONObject();
		a_host_tab_target.put("protocol", a_host_tab_target_protocol);
		a_host_tab_target_protocol.put("title", "我是房东");
		a_host_tab_target_protocol.put("pagetype", "childCate");
		a_host_tab_target_protocol.put("showsift", true);
		a_host_tab_target_protocol.put("list_name", "zufang");
		a_host_tab_target_protocol.put("showpub", false);
		a_host_tab_target_protocol.put("url", "https://houserent.m.58.com/landlord/center?topcate=house&city=@local@");
		a_host_tab_target.put("top_right_show", true);
		a_host_tab_target.put("isLogin", true);
		a_host_tab_target.put("showim", true);
		a_host_tab_target.put("top_right_text", "我是租客");
		a_host_tab_target.put("pagetype", "childCate");
		a_host_tab.put("isLogin", true);
}};