server:
  port: 9021 
spring: 
  application: 
    name: Consumer-F 
  cloud:
    gateway:
      routes:
      - id: after_route
        uri: http://httpbin.org:80/get
        filters:
        - AddRequestHeader=X-Request-Foo, Bar
        predicates:
        - After=2017-01-20T17:42:47.789-07:00[America/Denver]