
package com.yunhai.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "App", targetNamespace = "http://www.baidu.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface App {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "helloReturn", targetNamespace = "")
    @RequestWrapper(localName = "getSayHello", targetNamespace = "http://www.baidu.com", className = "com.yunhai.webservice.GetSayHello")
    @ResponseWrapper(localName = "getSayHelloResponse", targetNamespace = "http://www.baidu.com", className = "com.yunhai.webservice.GetSayHelloResponse")
    @Action(input = "http://www.baidu.com/App/getSayHelloRequest", output = "http://www.baidu.com/App/getSayHelloResponse")
    public String getSayHello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
