// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: abd.proto

package com.li.shao.ping.KeyListBase.datastructure.util.seria;

public final class MapData2 {
  private MapData2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MD2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:MD2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, string&gt; ddd = 1;</code>
     */
    int getDddCount();
    /**
     * <code>map&lt;string, string&gt; ddd = 1;</code>
     */
    boolean containsDdd(
        java.lang.String key);
    /**
     * Use {@link #getDddMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getDdd();
    /**
     * <code>map&lt;string, string&gt; ddd = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getDddMap();
    /**
     * <code>map&lt;string, string&gt; ddd = 1;</code>
     */

    java.lang.String getDddOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; ddd = 1;</code>
     */

    java.lang.String getDddOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code MD2}
   */
  public  static final class MD2 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MD2)
      MD2OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MD2.newBuilder() to construct.
    private MD2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MD2() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MD2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                ddd_ = com.google.protobuf.MapField.newMapField(
                    DddDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              ddd__ = input.readMessage(
                  DddDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              ddd_.getMutableMap().put(
                  ddd__.getKey(), ddd__.getValue());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.internal_static_MD2_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetDdd();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.internal_static_MD2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2.class, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2.Builder.class);
    }

    public static final int DDD_FIELD_NUMBER = 1;
    private static final class DddDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.internal_static_MD2_DddEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> ddd_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetDdd() {
      if (ddd_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            DddDefaultEntryHolder.defaultEntry);
      }
      return ddd_;
    }

    public int getDddCount() {
      return internalGetDdd().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; ddd = 1;</code>
     */

    public boolean containsDdd(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetDdd().getMap().containsKey(key);
    }
    /**
     * Use {@link #getDddMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getDdd() {
      return getDddMap();
    }
    /**
     * <code>map&lt;string, string&gt; ddd = 1;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getDddMap() {
      return internalGetDdd().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; ddd = 1;</code>
     */

    public java.lang.String getDddOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetDdd().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; ddd = 1;</code>
     */

    public java.lang.String getDddOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetDdd().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetDdd(),
          DddDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetDdd().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        ddd__ = DddDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, ddd__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2)) {
        return super.equals(obj);
      }
      com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2 other = (com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2) obj;

      boolean result = true;
      result = result && internalGetDdd().equals(
          other.internalGetDdd());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetDdd().getMap().isEmpty()) {
        hash = (37 * hash) + DDD_FIELD_NUMBER;
        hash = (53 * hash) + internalGetDdd().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MD2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MD2)
        com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.internal_static_MD2_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetDdd();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableDdd();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.internal_static_MD2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2.class, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2.Builder.class);
      }

      // Construct using com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableDdd().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.internal_static_MD2_descriptor;
      }

      @java.lang.Override
      public com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2 getDefaultInstanceForType() {
        return com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2.getDefaultInstance();
      }

      @java.lang.Override
      public com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2 build() {
        com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2 buildPartial() {
        com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2 result = new com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2(this);
        int from_bitField0_ = bitField0_;
        result.ddd_ = internalGetDdd();
        result.ddd_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2) {
          return mergeFrom((com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2 other) {
        if (other == com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2.getDefaultInstance()) return this;
        internalGetMutableDdd().mergeFrom(
            other.internalGetDdd());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> ddd_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetDdd() {
        if (ddd_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              DddDefaultEntryHolder.defaultEntry);
        }
        return ddd_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableDdd() {
        onChanged();;
        if (ddd_ == null) {
          ddd_ = com.google.protobuf.MapField.newMapField(
              DddDefaultEntryHolder.defaultEntry);
        }
        if (!ddd_.isMutable()) {
          ddd_ = ddd_.copy();
        }
        return ddd_;
      }

      public int getDddCount() {
        return internalGetDdd().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; ddd = 1;</code>
       */

      public boolean containsDdd(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetDdd().getMap().containsKey(key);
      }
      /**
       * Use {@link #getDddMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getDdd() {
        return getDddMap();
      }
      /**
       * <code>map&lt;string, string&gt; ddd = 1;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getDddMap() {
        return internalGetDdd().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; ddd = 1;</code>
       */

      public java.lang.String getDddOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetDdd().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; ddd = 1;</code>
       */

      public java.lang.String getDddOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetDdd().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearDdd() {
        internalGetMutableDdd().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; ddd = 1;</code>
       */

      public Builder removeDdd(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableDdd().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableDdd() {
        return internalGetMutableDdd().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; ddd = 1;</code>
       */
      public Builder putDdd(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableDdd().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; ddd = 1;</code>
       */

      public Builder putAllDdd(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableDdd().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MD2)
    }

    // @@protoc_insertion_point(class_scope:MD2)
    private static final com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2();
    }

    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MD2>
        PARSER = new com.google.protobuf.AbstractParser<MD2>() {
      @java.lang.Override
      public MD2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MD2(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MD2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MD2> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData2.MD2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MD2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MD2_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MD2_DddEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MD2_DddEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tabd.proto\"M\n\003MD2\022\032\n\003ddd\030\001 \003(\0132\r.MD2.Dd" +
      "dEntry\032*\n\010DddEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value" +
      "\030\002 \001(\t:\0028\001BA\n5com.li.shao.ping.KeyListBa" +
      "se.datastructure.util.seriaB\010MapData2b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MD2_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MD2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MD2_descriptor,
        new java.lang.String[] { "Ddd", });
    internal_static_MD2_DddEntry_descriptor =
      internal_static_MD2_descriptor.getNestedTypes().get(0);
    internal_static_MD2_DddEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MD2_DddEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
