// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: abd.proto

package com.li.shao.ping.KeyListBase.datastructure.util.seria;

import lombok.extern.slf4j.Slf4j;

public final class MapData {
  private MapData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MDOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MD)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .MD.Entity&gt; ddd = 1;</code>
     */
    int getDddCount();
    /**
     * <code>map&lt;string, .MD.Entity&gt; ddd = 1;</code>
     */
    boolean containsDdd(
        java.lang.String key);
    /**
     * Use {@link #getDddMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity>
    getDdd();
    /**
     * <code>map&lt;string, .MD.Entity&gt; ddd = 1;</code>
     */
    java.util.Map<java.lang.String, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity>
    getDddMap();
    /**
     * <code>map&lt;string, .MD.Entity&gt; ddd = 1;</code>
     */

    com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity getDddOrDefault(
        java.lang.String key,
        com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity defaultValue);
    /**
     * <code>map&lt;string, .MD.Entity&gt; ddd = 1;</code>
     */

    com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity getDddOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code MD}
   */
  public  static final class MD extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MD)
      MDOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MD.newBuilder() to construct.
    private MD(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MD() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MD(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                ddd_ = com.google.protobuf.MapField.newMapField(
                    DddDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity>
              ddd__ = input.readMessage(
                  DddDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              ddd_.getMutableMap().put(
                  ddd__.getKey(), ddd__.getValue());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.internal_static_MD_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetDdd();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.internal_static_MD_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.class, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Builder.class);
    }

    public interface EntityOrBuilder extends
        // @@protoc_insertion_point(interface_extends:MD.Entity)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string val = 1;</code>
       */
      java.lang.String getVal();
      /**
       * <code>string val = 1;</code>
       */
      com.google.protobuf.ByteString
          getValBytes();

      /**
       * <code>int32 status = 2;</code>
       */
      int getStatus();
    }
    /**
     * Protobuf type {@code MD.Entity}
     */
    public  static final class Entity extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:MD.Entity)
        EntityOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Entity.newBuilder() to construct.
      private Entity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      public Entity() {
        val_ = "";
        status_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Entity(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                val_ = s;
                break;
              }
              case 16: {

                status_ = input.readInt32();
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.internal_static_MD_Entity_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.internal_static_MD_Entity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity.class, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity.Builder.class);
      }

      public static final int VAL_FIELD_NUMBER = 1;
      private volatile java.lang.Object val_;
      /**
       * <code>string val = 1;</code>
       */
      public java.lang.String getVal() {
        java.lang.Object ref = val_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          val_ = s;
          return s;
        }
      }
      /**
       * <code>string val = 1;</code>
       */
      public com.google.protobuf.ByteString
          getValBytes() {
        java.lang.Object ref = val_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          val_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int STATUS_FIELD_NUMBER = 2;
      private int status_;
      /**
       * <code>int32 status = 2;</code>
       */
      public int getStatus() {
        return status_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getValBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, val_);
        }
        if (status_ != 0) {
          output.writeInt32(2, status_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getValBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, val_);
        }
        if (status_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, status_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity)) {
          return super.equals(obj);
        }
        com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity other = (com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity) obj;

        boolean result = true;
        result = result && getVal()
            .equals(other.getVal());
        result = result && (getStatus()
            == other.getStatus());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + VAL_FIELD_NUMBER;
        hash = (53 * hash) + getVal().hashCode();
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code MD.Entity}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:MD.Entity)
          com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.EntityOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.internal_static_MD_Entity_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.internal_static_MD_Entity_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity.class, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity.Builder.class);
        }

        // Construct using com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          val_ = "";

          status_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.internal_static_MD_Entity_descriptor;
        }

        @java.lang.Override
        public com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity getDefaultInstanceForType() {
          return com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity.getDefaultInstance();
        }

        @java.lang.Override
        public com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity build() {
          com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity buildPartial() {
          com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity result = new com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity(this);
          result.val_ = val_;
          result.status_ = status_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity) {
            return mergeFrom((com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity other) {
          if (other == com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity.getDefaultInstance()) return this;
          if (!other.getVal().isEmpty()) {
            val_ = other.val_;
            onChanged();
          }
          if (other.getStatus() != 0) {
            setStatus(other.getStatus());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object val_ = "";
        /**
         * <code>string val = 1;</code>
         */
        public java.lang.String getVal() {
          java.lang.Object ref = val_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            val_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string val = 1;</code>
         */
        public com.google.protobuf.ByteString
            getValBytes() {
          java.lang.Object ref = val_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            val_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string val = 1;</code>
         */
        public Builder setVal(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          val_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string val = 1;</code>
         */
        public Builder clearVal() {
          
          val_ = getDefaultInstance().getVal();
          onChanged();
          return this;
        }
        /**
         * <code>string val = 1;</code>
         */
        public Builder setValBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          val_ = value;
          onChanged();
          return this;
        }

        private int status_ ;
        /**
         * <code>int32 status = 2;</code>
         */
        public int getStatus() {
          return status_;
        }
        /**
         * <code>int32 status = 2;</code>
         */
        public Builder setStatus(int value) {
          
          status_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 status = 2;</code>
         */
        public Builder clearStatus() {
          
          status_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:MD.Entity)
      }

      // @@protoc_insertion_point(class_scope:MD.Entity)
      private static final com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity();
      }

      public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Entity>
          PARSER = new com.google.protobuf.AbstractParser<Entity>() {
        @java.lang.Override
        public Entity parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Entity(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Entity> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Entity> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int DDD_FIELD_NUMBER = 1;
    private static final class DddDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity>newDefaultInstance(
                  com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.internal_static_MD_DddEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity> ddd_;
    private com.google.protobuf.MapField<java.lang.String, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity>
    internalGetDdd() {
      if (ddd_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            DddDefaultEntryHolder.defaultEntry);
      }
      return ddd_;
    }

    public int getDddCount() {
      return internalGetDdd().getMap().size();
    }
    /**
     * <code>map&lt;string, .MD.Entity&gt; ddd = 1;</code>
     */

    public boolean containsDdd(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetDdd().getMap().containsKey(key);
    }
    /**
     * Use {@link #getDddMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity> getDdd() {
      return getDddMap();
    }
    /**
     * <code>map&lt;string, .MD.Entity&gt; ddd = 1;</code>
     */

    public java.util.Map<java.lang.String, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity> getDddMap() {
      return internalGetDdd().getMap();
    }
    /**
     * <code>map&lt;string, .MD.Entity&gt; ddd = 1;</code>
     */

    public com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity getDddOrDefault(
        java.lang.String key,
        com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity> map =
          internalGetDdd().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .MD.Entity&gt; ddd = 1;</code>
     */

    public com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity getDddOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity> map =
          internalGetDdd().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetDdd(),
          DddDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity> entry
           : internalGetDdd().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity>
        ddd__ = DddDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, ddd__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD)) {
        return super.equals(obj);
      }
      com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD other = (com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD) obj;

      boolean result = true;
      result = result && internalGetDdd().equals(
          other.internalGetDdd());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetDdd().getMap().isEmpty()) {
        hash = (37 * hash) + DDD_FIELD_NUMBER;
        hash = (53 * hash) + internalGetDdd().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MD}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MD)
        com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MDOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.internal_static_MD_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetDdd();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableDdd();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.internal_static_MD_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.class, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Builder.class);
      }

      // Construct using com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableDdd().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.internal_static_MD_descriptor;
      }

      @java.lang.Override
      public com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD getDefaultInstanceForType() {
        return com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.getDefaultInstance();
      }

      @java.lang.Override
      public com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD build() {
        com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD buildPartial() {
        com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD result = new com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD(this);
        int from_bitField0_ = bitField0_;
        result.ddd_ = internalGetDdd();
        result.ddd_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD) {
          return mergeFrom((com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD other) {
        if (other == com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.getDefaultInstance()) return this;
        internalGetMutableDdd().mergeFrom(
            other.internalGetDdd());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity> ddd_;
      private com.google.protobuf.MapField<java.lang.String, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity>
      internalGetDdd() {
        if (ddd_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              DddDefaultEntryHolder.defaultEntry);
        }
        return ddd_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity>
      internalGetMutableDdd() {
        onChanged();;
        if (ddd_ == null) {
          ddd_ = com.google.protobuf.MapField.newMapField(
              DddDefaultEntryHolder.defaultEntry);
        }
        if (!ddd_.isMutable()) {
          ddd_ = ddd_.copy();
        }
        return ddd_;
      }

      public int getDddCount() {
        return internalGetDdd().getMap().size();
      }
      /**
       * <code>map&lt;string, .MD.Entity&gt; ddd = 1;</code>
       */

      public boolean containsDdd(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetDdd().getMap().containsKey(key);
      }
      /**
       * Use {@link #getDddMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity> getDdd() {
        return getDddMap();
      }
      /**
       * <code>map&lt;string, .MD.Entity&gt; ddd = 1;</code>
       */

      public java.util.Map<java.lang.String, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity> getDddMap() {
        return internalGetDdd().getMap();
      }
      /**
       * <code>map&lt;string, .MD.Entity&gt; ddd = 1;</code>
       */

      public com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity getDddOrDefault(
          java.lang.String key,
          com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity> map =
            internalGetDdd().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .MD.Entity&gt; ddd = 1;</code>
       */

      public com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity getDddOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity> map =
            internalGetDdd().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearDdd() {
        internalGetMutableDdd().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .MD.Entity&gt; ddd = 1;</code>
       */

      public Builder removeDdd(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableDdd().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity>
      getMutableDdd() {
        return internalGetMutableDdd().getMutableMap();
      }
      /**
       * <code>map&lt;string, .MD.Entity&gt; ddd = 1;</code>
       */
      public Builder putDdd(
          java.lang.String key,
          com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableDdd().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .MD.Entity&gt; ddd = 1;</code>
       */

      public Builder putAllDdd(
          java.util.Map<java.lang.String, com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD.Entity> values) {
        internalGetMutableDdd().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MD)
    }

    // @@protoc_insertion_point(class_scope:MD)
    private static final com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD();
    }

    public static com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MD>
        PARSER = new com.google.protobuf.AbstractParser<MD>() {
      @java.lang.Override
      public MD parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MD(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MD> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MD> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.li.shao.ping.KeyListBase.datastructure.util.seria.MapData.MD getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MD_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MD_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MD_Entity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MD_Entity_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MD_DddEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MD_DddEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tabd.proto\"~\n\002MD\022\031\n\003ddd\030\001 \003(\0132\014.MD.DddE" +
      "ntry\032%\n\006Entity\022\013\n\003val\030\001 \001(\t\022\016\n\006status\030\002 " +
      "\001(\005\0326\n\010DddEntry\022\013\n\003key\030\001 \001(\t\022\031\n\005value\030\002 " +
      "\001(\0132\n.MD.Entity:\0028\001B@\n5com.li.shao.ping." +
      "KeyListBase.datastructure.util.seriaB\007Ma" +
      "pDatab\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MD_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MD_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MD_descriptor,
        new java.lang.String[] { "Ddd", });
    internal_static_MD_Entity_descriptor =
      internal_static_MD_descriptor.getNestedTypes().get(0);
    internal_static_MD_Entity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MD_Entity_descriptor,
        new java.lang.String[] { "Val", "Status", });
    internal_static_MD_DddEntry_descriptor =
      internal_static_MD_descriptor.getNestedTypes().get(1);
    internal_static_MD_DddEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MD_DddEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
